### ISSUE TITLE
It is not possible to deploy the Webhook and Agents in the same namespace

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-mutating-webhook#44]
If you deploy the webhook and the Agents in the default namespace, the mutation does not happen, so the Agent is not configured to report APM. The same configuration on webhook and Agents works if the webhook is deployed in the namespace `elastic-apm`

This is the webhook configuration used.
```
apm:
  secret_token: SuP3RT0K3N
  namespaces:
    - default
webhookConfig:
  agents:
    java:
      image: docker.elastic.co/observability/apm-agent-java:1.33.0
      artifact: "/usr/agent/elastic-apm-agent.jar"
      environment:
        JAVA_TOOL_OPTIONS: "-javaagent:/elastic/apm/agent/elastic-apm-agent.jar"
        ELASTIC_APM_SERVER_URL: "https://apm-example.com:8200"
        ELASTIC_APM_ENVIRONMENT: "prod"
        ELASTIC_APM_LOG_LEVEL: "info"
```
